version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: smartstock_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
      POSTGRES_DB: smartstock_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: smartstock_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - smartnet

networks:
  smartnet:

volumes:
  postgres_data:
